# Playing around with Torch

In [1]:
import torch
import numpy as np

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [2]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
display(torch.ones_like(x_np))
display(torch.ones_like(x_np, dtype=torch.float))

display(torch.rand_like(x_np, dtype=torch.float))

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

tensor([[0.6926, 0.3047, 0.3078],
        [0.1662, 0.5870, 0.3211],
        [0.8636, 0.0730, 0.2914]])

In [4]:
shape = (3,3,)
display(torch.rand(shape))
display(torch.ones(shape))
display(torch.zeros(shape))

rand_tensor = torch.rand(shape)

tensor([[0.8827, 0.6595, 0.4358],
        [0.4490, 0.5012, 0.3638],
        [0.3348, 0.9670, 0.0726]])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
display(rand_tensor.shape)
display(rand_tensor.device)
display(rand_tensor.dtype)

torch.Size([3, 3])

device(type='cpu')

torch.float32

Go to [here](https://pytorch.org/docs/stable/torch.html) for a full list of torch operations.

In [6]:
rand_tensor.numel() # total number of elements

9

In [7]:
tmp = torch.arange(1, 10, 1).reshape(3,3)
display(tmp)
chunked = tmp.chunk(3)
display(chunked)

display(torch.column_stack(chunked))
display(torch.cat(chunked))
display(torch.dstack(chunked))
display(torch.dstack(chunked)[:,:,0])
display(torch.vstack(chunked))
display(torch.hstack(chunked))
display(tmp.masked_select(tmp >4))
display((torch.hstack(chunked), torch.hstack(chunked).squeeze()))


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

(tensor([[1, 2, 3]]), tensor([[4, 5, 6]]), tensor([[7, 8, 9]]))

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor([[[1, 4, 7],
         [2, 5, 8],
         [3, 6, 9]]])

tensor([[1, 2, 3]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

tensor([5, 6, 7, 8, 9])

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [8]:
torch.cuda.is_available()

False

What the grad arguments mean, `require_grad` specifies whther to keep track of the operations the variables are involved in.

In [9]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 + b**2
Q

tensor([60., 97.], grad_fn=<AddBackward0>)

In [10]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)
external_grad

tensor([1., 1.])

In [11]:
all(a.grad == 9*a**2)

True

Fromt pytorch tutorial

**A Recipe for a neural net training**
- model with some learnable params(or weights)
- iterate over a dataset of inputs
- process input through the network
- compute the loss
- propagate grads back into network parameters
- update the weights using a simple rule(like weight=weighte - lr* gradient)




- model is a class with `__init__` , and `forward`, and if any other thing
- you can `print` the model or see the `.parameters()`
- zero the grad 
- and do backward

Recap:
- `torch.Tensor` - A multi-dimensional array with support for *autograd* operations like `backward()`. Also *holds* the *gradient* w.r.t. the tensor.
- `nn.Module` - Neural network module. Convenient way of encapsulating *parameters*, with *helpers* for moving them to *GPU*, *exporting*, *loading*, etc.
- `nn.Parameter` - A kind of Tensor, that is automatically registered as a parameter when assigned as an attribute to a Module.
- `autograd.Function` - Implements `forward` and `backward` definitions of an autograd operation. Every Tensor operation creates at least a single Function node that connects to functions that created a Tensor and encodes its history.

then define a loss
- make sure output and the target are of the same shape
- use a loss function on them

Backprop:
- zero the gradient buffers for all params `zero_grad()`
- and do `backward()`

Now update params
- torch has an optim that helps with that with `step`
    - so optimizer definition like `optimizer = optim.SGD(...)`
    - `optimizer.zero_grad()`
    - create output from the model given the input output = model(input)
    - given the loss criterion define loss, `loss = criterion(output, target)`
    - do backward `loss.backward()`
    - update the params `optimizer.step()`
